# WARNING: This is a DEVELOPMENT docker-compose file used for development of the entire app, it should not be used for production.
version: "3"
services:

  npm:
    image: nginxproxymanager:dev
    build:
      context: ./
      dockerfile: ./dev/Dockerfile
    ports:
      - 3080:80
      - 3081:81
      - 3443:443
    environment:
      - DEVELOPMENT=true
      - GOPROXY=${GOPROXY:-}
      - GOPRIVATE=${GOPRIVATE:-}
      - LOG_LEVEL=debug
      - PUID=1000
      - PGID=1000
    volumes:
      - ../:/app
      - ./rootfs/var/www/html:/var/www/html
      - ../data:/data
    working_dir: /app
    networks:
      default:
        aliases:
          - website1.internal
          - website2.internal
          - website3.internal

  stepca:
    image: nginxproxymanager/testca
    networks:
      default:
        aliases:
          - ca.internal

  swagger:
    image: swaggerapi/swagger-ui:latest
    ports:
      - 3001:80
    environment:
      URL: "http://${SWAGGER_PUBLIC_DOMAIN:-127.0.0.1:3081}/api/schema"
      PORT: '80'
    depends_on:
      - npm
